function print_usage
    echo "Usage: nuke.fish [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --providers-only          Destroy only provider infrastructure (AWS/Azure)"
    echo "  --run-id <id>             Only destroy resources for specific run"
    echo "  -h, --help                Show this help"
    echo ""
    echo "Modes:"
    echo "  Default (no options):     Destroy ALL rb_managed resources (no prompts)"
    echo "  Providers (--providers-only):  Destroy AWS/Azure, preserve orchestrator/meta"
    echo "  Targeted (--run-id):      Destroy only resources with matching rb_run_id"
    echo ""
    echo "Examples:"
    echo "  nuke.fish                        Destroy everything without prompts"
    echo "  nuke.fish --providers-only       Destroy providers, keep orchestrator"
    echo "  nuke.fish --run-id 1736012345    Destroy only run 1736012345"
end
