function print_usage
    echo "Usage: nuke.fish [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -f, --force, -y, --yes    Skip confirmation prompts"
    echo "  --run-id <id>             Only destroy resources for specific run"
    echo "  -h, --help                Show this help"
    echo ""
    echo "Modes:"
    echo "  Default (no --run-id):    Destroy ALL rb_managed resources"
    echo "  Targeted (--run-id):      Destroy only resources with matching rb_run_id"
    echo ""
    echo "Examples:"
    echo "  nuke.fish                        Interactive cleanup of ALL resources"
    echo "  nuke.fish --force                Destroy everything without prompts"
    echo "  nuke.fish --run-id 1736012345    Destroy only run 1736012345"
end
